[versions]
minecraft = "26.2"
mcRange = "~26.2"
fabric-api = "0.152.0+26.2"
skyblock-api = "4.2.6"
modmenu = "18.0.0-alpha.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
skyblock-api = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblock-api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
